SRC_HC_OPTS += -optl-pthread
SRC_HC_OPTS += -optl-B/usr/bin/ld.gold
SRC_HC_OPTS += -H32m -O1 -fPIC
SRC_CC_OPTS          += -O0 -fasm -fPIC
GhcStage1HcOpts      += -O0 -fasm -fPIC
GhcStage2HcOpts      += -O2 -fasm -fPIC
GhcLibHcOpts         += -O0 -fasm -fPIC
GhcHcOpts += -Rghc-timing -fPIC
SplitObjs = NO
STRIP = :
GhcRtsCcOpts += -O0
GhcRtsWays += p
V               = 0
BeConservative  = YES
