FROM mitchty/alpine-ghc:latest

ENV username "Mitch Tishmack"
ENV useremail mitch.tishmack@gmail.com
ENV builduser build

USER root
RUN apk update && apk add git abuild && \
    echo "PACKAGER='$username <$useremail>'" >> /etc/abuild.conf

RUN adduser -D $builduser && \
    addgroup $builduser abuild && \
    mkdir -p /var/cache/distfiles && \
    chgrp abuild /var/cache/distfiles && \
    chmod g+w /var/cache/distfiles && \
    echo $builduser  "ALL=(ALL) ALL" > /etc/sudoers

USER $builduser
WORKDIR /home/$builduser
RUN git config --global user.name '$username' && \
    git config --global user.email '$useremail' && \
    git clone --depth 1 git://dev.alpinelinux.org/aports && \
    abuild-keygen -a -i

USER root
RUN rm -fr /home/$builduser/.abuild/*.rsa*

COPY alpine-keys.tar /home/$builduser/.abuild/alpine-keys.tar
RUN find /home/$builduser \! -user $builduser -exec chown -R $builduser:$builduser {} \;
USER $builduser
WORKDIR /tmp
RUN cd /home/$builduser/.abuild && tar xvf alpine-keys.tar
COPY alpine-ghc/next/x86_64 /home/$builduser/packages/testing/x86_64
USER root
RUN find /home/$builduser \! -user $builduser -exec chown -R $builduser:$builduser {} \;
USER $builduser
RUN apk index -o /home/$builduser/packages/testing/x86_64/APKINDEX.unsigned.tar.gz `find /home/$builduser/packages/testing/x86_64 -name '*.apk'` || /bin/true
USER root
RUN rm /home/$builduser/packages/testing/x86_64/APKINDEX.tar.gz
RUN cp /home/$builduser/packages/testing/x86_64/APKINDEX.unsigned.tar.gz /home/$builduser/packages/testing/x86_64/APKINDEX.tar.gz
RUN find /home/$builduser \! -user $builduser -exec chown -R $builduser:$builduser {} \;
RUN abuild-sign -k /home/$builduser/.abuild/*.rsa /home/$builduser/packages/testing/x86_64/APKINDEX.tar.gz
RUN cp /home/$builduser/.abuild/*.pub /etc/apk/keys && chmod o+r /etc/apk/keys/*.pub
