FROM ghcapk:latest

ENV username "Mitch Tishmack"
ENV useremail mitch.tishmack@gmail.com
ENV builduser build

USER root
RUN apk update && apk add git abuild && rm /home/$builduser/.abuild/* && \
    echo "PACKAGER='$username <$useremail>'" >> /etc/abuild.conf

USER build
WORKDIR $HOME
COPY alpine-keys.tar /home/$builduser/.abuild/alpine-keys.tar
RUN cd /home/$builduser/.abuild && tar xvf alpine-keys.tar
RUN rm /home/$builduser/packages/testing/x86_64/APKINDEX.tar.gz && \
    apk index -o /home/$builduser/packages/testing/x86_64/APKINDEX.unsigned.tar.gz /home/$builduser/packages/testing/x86_64/*.apk && \
    cp /home/$builduser/packages/testing/x86_64/APKINDEX.unsigned.tar.gz /home/$builduser/packages/testing/x86_64/APKINDEX.tar.gz && \
    abuild-sign -k /home/$builduser/.abuild/*.rsa /home/$builduser/packages/testing/x86_64/APKINDEX.tar.gz

USER root
RUN cp /home/$builduser/.abuild/*.pub /etc/apk/keys && chmod o+r /etc/apk/keys/*.pub
